object frmTest: TfrmTest
  Left = 0
  Top = 0
  Caption = 'Test form'
  ClientHeight = 288
  ClientWidth = 465
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object BitBtn1: TBitBtn
    Tag = -2
    Left = 8
    Top = 200
    Width = 201
    Height = 81
    Caption = 'History'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 0
  end
  object BitBtn2: TBitBtn
    Tag = 1
    Left = 240
    Top = 72
    Width = 201
    Height = 53
    Caption = 'Interface "uses"'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 1
  end
  object BitBtn3: TBitBtn
    Tag = 1
    Left = 240
    Top = 8
    Width = 201
    Height = 53
    Caption = 'Implementation "uses"'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 2
  end
  object BitBtn4: TBitBtn
    Tag = 1
    Left = 8
    Top = 8
    Width = 201
    Height = 81
    Caption = 'Navigation'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 3
  end
  object BitBtn5: TBitBtn
    Tag = 1
    Left = 8
    Top = 104
    Width = 201
    Height = 81
    Caption = 'Units'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -17
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 4
  end
  object BitBtn6: TBitBtn
    Tag = 3
    Left = 240
    Top = 131
    Width = 201
    Height = 53
    Caption = 'Open'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = []
    NumGlyphs = 2
    ParentFont = False
    TabOrder = 5
  end
end
